// Mocks generated by Mockito 5.4.6 from annotations
// in workshop5/test/connectivity_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:workshop5/connectivity_service.dart' as _i2;
import 'package:workshop5/queue_provider.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i2.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [QueueProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueProvider extends _i1.Mock implements _i4.QueueProvider {
  MockQueueProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get clients =>
      (super.noSuchMethod(
            Invocation.getter(#clients),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> get rooms =>
      (super.noSuchMethod(
            Invocation.getter(#rooms),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  String getRoomName(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomName, [roomId]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getRoomName, [roomId]),
            ),
          )
          as String);

  @override
  void setupConnectivityListener(void Function()? onConnectivityChanged) =>
      super.noSuchMethod(
        Invocation.method(#setupConnectivityListener, [onConnectivityChanged]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> onConnectivityRestored() =>
      (super.noSuchMethod(
            Invocation.method(#onConnectivityRestored, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchWaitingRooms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWaitingRooms, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> addClient(
    String? name, {
    String? chosenRoomId,
    String? deviceToken,
    bool? enableNotifications = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addClient,
              [name],
              {
                #chosenRoomId: chosenRoomId,
                #deviceToken: deviceToken,
                #enableNotifications: enableNotifications,
              },
            ),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> removeClient(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeClient, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> nextClient() =>
      (super.noSuchMethod(
            Invocation.method(#nextClient, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> subscribeToRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToRoom, [roomId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
