// Mocks generated by Mockito 5.4.6 from annotations
// in workshop5/test/queue_provider_geolocation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:geolocator/geolocator.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:workshop5/geolocation_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GeolocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocationService extends _i1.Mock
    implements _i2.GeolocationService {
  MockGeolocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> requestPermissionAtStartup() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissionAtStartup, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Position?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i3.Future<_i4.Position?>.value(),
          )
          as _i3.Future<_i4.Position?>);
}
